//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int cutomerid { get; set; }
        public int productid { get; set; }
        public int quantity { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Products Products { get; set; }
    }
}
